### 지난주 복습 230109 ~ 230113 ###

In [ ]:
#class
class Student:
    def __init__(self):                 # self를 넣어줌으로 hello라는 속성을 부여함
        self.hello = "안녕하세요"

In [33]:
# stu_a, stu_b는 독립적인 존재
stu_a = Student() # 클래스로부터 인스턴스 초기화
stu_b = Student() # 클래스로부터 인스턴스 초기화

In [34]:
stu_a.hello = "안녕하세요"

In [35]:
stu_a.hello = "학생A"

In [36]:
print(stu_a.hello)

학생A


In [37]:
print(stu_b.hello)

안녕하세요


In [63]:
# class
class Student:
    def __init__(self):                   # self를 넣어줌으로 hello라는 속성을 부여함
                 self.hello = "안녕하세요"
    def greeting(self):
        print(self.hello)

In [64]:
stu_a.greetiong = "안녕하세요"

In [65]:
stu_b.greetiong = "안녕하세요"

In [66]:
class Person:
    def __init__(self,name,age):                   # self를 넣어줌으로 hello라는 속성을 부여함
        self.name = name
        self.age = age

In [69]:
p1 = Person("name1",40)
p2 = Person("name2",32)

In [73]:
p1. __dict__     # __dict__속성을 볼수 있음

{'name': 'name1', 'age': 40}

In [71]:
p2. __dict__

{'name': 'name2', 'age': 32}

In [74]:
# p1. name = "name1"
# p1. age = 40

# p2. name = "name2"
# p2. age = 32

In [75]:
class Person2:
    def __init__(self, name, age, address):
        self.hello = "안녕하세요"
        self. name = name
        self. age = age
        self. address = address
    def greeting(self):
        print(f'{self.hello} 제 이름은 {self. name}입니다.')

In [76]:
maria = Person2("마리아", 23, "서울시 마포구")
maria.greeting()

안녕하세요 제 이름은 마리아입니다.


In [126]:
# Person 클래스로 maria, james라는 인스턴스를 생성합니다. 
# maria james 두 사람의 나이, 이름, 주소를 받아와 객체에 저장하고 화면에 출력

class Person:
    def __init__(self,second):
        self.name = input('이름은 무엇인가요?:')
        self.age = input('나이은 무엇인가요?:')
        self.address = input('주소는 무엇인가요?:')
        self.second = second
    def greeting(self):
        print(f'{self.second}이름:{self.name}', f'\n{self.second}나이:{self.age}', f'\n{self.second}주소:{self.address}')

In [129]:
maria = Person('첫번째')
james = Person('두번째')
maria.greeting()
james.greeting()

이름은 무엇인가요?: 마리아
나이은 무엇인가요?: 20
주소는 무엇인가요?: 서울시 강남구
이름은 무엇인가요?: 제임스
나이은 무엇인가요?: 21
주소는 무엇인가요?: 서울시 구로구


첫번째이름:마리아 
첫번째나이:20 
첫번째주소:서울시 강남구
두번째이름:제임스 
두번째나이:21 
두번째주소:서울시 구로구


### Class 비공개 속성 사용하기
#### 인스턴스.속성 = 값 을 통해 새롭게 인스턴트 속성값을 변경 못하도록 막고 싶을 때는 비공개 속성을 사용
#### 사용법은 (__) 던더를 사용하면 됨

In [145]:
class Person3:
    def __init__(self, name, age, address, wallet):
        self.hello = "안녕하세요."
        self.name = name
        self.age = age
        self.address = address
        self.__wallet = wallet          ### 변수 앞에 __를 붙여서 비공개 속성으로 전환
    def greeting(self):
        print(f"{self.hello} 제 이름은 {self.name}입니다.")
    def amount(self):
        print(self.__wallet)

In [146]:
jink.amount()

10000


In [144]:
jink = Person3('강지인',97, "경기도 의정부", 10000)
print(jink.hello)
print(jink.name)
print(jink.age)
print(jink.address)
print(jink.__wallet)    ## (__ 으로 속성을 비공개로 클래스 영역 바깥에서는 사용할 수 없다)

안녕하세요.
강지인
97
경기도 의정부


AttributeError: 'Person3' object has no attribute '__wallet'

In [148]:
class Person3:
    def __init__(self, name, age, address, wallet):
        self.hello = "안녕하세요."
        self.name = name
        self.age = age
        self.address = address
        self.__wallet = wallet          ### 변수 앞에 __를 붙여서 비공개 속성으로 전환
    
    def pay(self, amount):
        if self.__wallet < amount:
            print("돈이 모자랍니다.")
            return
        self.__wallet -= amount

In [149]:
jink.amount()

10000


In [ ]:
input("체력, 마나, ap를 입력하세요.")

In [165]:
# 사용자로부터 체력, 마나, ap를 입력 받아옵니다. 주어진 코드에서 애니(annie)클래스를 작성하고 티버(tibbers)스킬의 피해량이 출력되게 만들어보라.
# 티버의 피해량은 ap*0.65 + 400이며 ap는 마법 능력치를 뜻한다.    #511.68 334.0 298

class Annie:
    def __init__(self, hp, mp, ap, dps):
        self.hp = hp #input("체력, 마나, ap를 입력하세요.")
        self.mp = mp
        self.ap = ap
        self.dps = dps
        
    def lol(self):
        print(f'티버: 피해량 {self.dps}')

In [166]:
hp,mp,ap = map(float,input("체력, 마나, ap를 입력하세요.").split())
dps = ap * 0.65 + 400
game = Annie(hp,mp,ap,dps)
game.lol()

체력, 마나, ap를 입력하세요. 511.68 334.0 298


티버: 피해량 593.7


In [169]:
class Annie:
    def __init__(self, hp, mp, ap):
        self.hp = hp #input("체력, 마나, ap를 입력하세요.")
        self.mp = mp
        self.ap = ap
        self.dps = dps
        
    def lol(self):
        print(f'티버: 피해량 {self.dps * 0.65 + 400}')
        

In [171]:
hp,mp,ap = map(float,input("체력, 마나, ap를 입력하세요.").split())
game = Annie(hp =hp, mp = mp, ap = ap)
game.lol()

체력, 마나, ap를 입력하세요. 511.68 334.0 298


티버: 피해량 785.905


In [173]:
class Person3:
    def __init__(self, name, age, address, wallet):
        self.hello = "안녕하세요."
        self.name = name
        self.age = age
        self.address = address
        self.__wallet = wallet          ### 변수 앞에 __를 붙여서 비공개 속성으로 전환
    
    def pay(self, amount):
        if self.__wallet < amount:
            print("돈이 모자랍니다.")
            return
        self.__wallet -= amount
        
    @classmethod
    def from_string(cls, str):
        name, age, address, __wallet = string.split(',')
        return cls(name, age, address, __wallet)
    
    # @staticmethod
    # def (self, cls 안쓰는 경우)

## 넘파이 배열(NumPy)
- python 내장 모듈이 아님 -> 별도로 설치 요구 (anaconda를 환경으로 꾸렸기 때문에 NumPy 패키지를 설치없이 사용가능
- 공식 홈페이지 numpy.org
- 숫자 데이터 효과적으로 다룰수 있음 -> 데이터를 주로 다룸. 데이터 과학 및 데이터 분석에 많이 사용
- 다차원 배열 자료구조 클래스인 ndarray클래스를 지원 -> 백터와 행렬을 사용하는 선형대수 계산에 사용
- 배열(Array)이란 순서가 있는 같은 종류(type)의 데이터가 저장되는 자료형
- python리스트(좋은 자료형 맞음)보다 넘파이 배열이 구조적으로 속도가 빠르고, 메모리를 더 적게 사용

- data : 이진 데이터
- dimensions : 배열 구조
- strides : 증감
- 크기(type의 크기)
- length : 시퀀스 길이
- items : 요소(주소)

#### 넘파이 배열 
- 넘파이 패키지의 배열(Array)는 리스트보다 적은 메모리로 많은 데이터를 빠르게 처리 가능
1. 모든 요소(items)가 같은 자료형(type)이어야 함 (리스트는 다양한 자료형을 섞어서 사용가능)
2. 
- 넘파이의 배열 연산은 C로 구현된 내부 반복문을 사용 -> python 반복문보다 속도가 빠름
- 백터화 연산을 이용해 간단한 코드로 복잡한 연산 수행 가능
- 배열 인덱싱을 사용한 질의 기능을 이용 -> 간단한 코드로 복잡한 수식 계산

### 넘파이 패키지 임포트하기
- 별칭은 np <- 라는 이름으로 임포트 하는 것이 관례(np : NumPy 패키지)
- 임포트 하는 코드는 < import numpy as np >

#### 1차원 배열 만들기
- 배열 객체인 ndarray는 N - dimensional Array 의 약자
- 1차~3차원 배열
- np의 array메서드 인수(np.array(시퀀스))로 시퀀스 자료형을 넣으면 넘파이 배열로 변환
- ndarray 객체의 표현식을 보면 바깥쪽에 array() 붙어있음. 배열 객체와 리스트는 많은 차이가 있다.
- np 배열 객체의 속성 중 shape을 사용하면 np배열의 모양을 확인할 수 있다

In [174]:
!conda list

# packages in environment at C:\Users\Playdata\anaconda3:
#
# Name                    Version                   Build  Channel
_ipyw_jlab_nb_ext_conf    0.1.0            py39haa95532_0  
alabaster                 0.7.12             pyhd3eb1b0_0  
anaconda                  2022.10                  py39_0  
anaconda-client           1.11.0           py39haa95532_0  
anaconda-navigator        2.3.1            py39haa95532_0  
anaconda-project          0.11.1           py39haa95532_0  
anyio                     3.5.0            py39haa95532_0  
appdirs                   1.4.4              pyhd3eb1b0_0  
argon2-cffi               21.3.0             pyhd3eb1b0_0  
argon2-cffi-bindings      21.2.0           py39h2bbff1b_0  
arrow                     1.2.2              pyhd3eb1b0_0  
astroid                   2.11.7           py39haa95532_0  
astropy                   5.1              py39h080aedc_0  
atomicwrites              1.4.0                      py_0  
attrs                     21.4.0 

In [193]:
# NumPy를 임포트
# jupyter lab에서 1회만 실행하면 그 아래 코드에서는 다 사용 가능
import numpy as np

In [194]:
ar = np.array([_ for _ in range(10)])
ar

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [195]:
ar.shape

(10,)

In [196]:
type(ar)

numpy.ndarray

In [197]:
ar2 = np.array([1.2, 2, 5, 7, 6.2])
ar2

array([1.2, 2. , 5. , 7. , 6.2])

### 넘파이의 자료형
- 넘파이의 배열인 ndarray클래스는 요소가 모두 같은 자료형을 가짐
- np.array()함수로 배열을 만들때 자료형을 명시적으로 작성해야 함 -> 키워드 인자로 dtype을 사용
- 반대로 dtype 키워드 인수가 없으면 데이터 자료형을 동적 타이핑한다
- 만들어진 넘파이 배열의 자료형을 확인 시 dtype 속성 활용

In [198]:
ar.dtype

dtype('int32')

In [199]:
ar2.dtype

dtype('float64')

In [200]:
# 01010101 -> 8bits == 1byte

#### 넘파이의 자료형 ->책 p122 '?' boolean type 이게 맞음
- np.array() 메서드를 쓸 때 dtype 키워드 인수로 지정할 자료형의 값
- 무한대를 표현하기 위한 np.inf(infinity)
- 정의할 수 없는 숫자 np.nan(not a number)를 사용
- ex) 1을 0으로 나누려고 하거나 0에 대한 로그 값을 계산하면 무한대인 np.inf가 나옴 -> 0을 0으로 나누려고 시도하면 np.nan이 나옴

In [215]:
ar3 = np.array([_ for _ in range(3, 10, 3)],"i8")   # int8bytes -->  * 8bit
ar3
print(ar3)
print(ar3.dtype)

[3 6 9]
int64


In [216]:
ar4 = np.array([_ for _ in range(2, 10, 2)],"f8")
print(ar4)
print(ar4.dtype)

[2. 4. 6. 8.]
float64


In [217]:
ar5 = np.array(["가나다라마" for _ in range(5)],"U5")      #

print(ar5)         
print(ar5.dtype)        # <U8은 최대 8글자의 유니코드 자료형
                       #### [유니코드 8글자 자료형을 명시적으로 선언

['가나다라마' '가나다라마' '가나다라마' '가나다라마' '가나다라마']
<U5


### 백터화 연산(Vectorized Operation)
- 배열의 각 요소에 대한 반복 연산을 하나의 명령어로 처리하는 벡터화 연산을 지원
- 리스트 내 모든 요소 데이터를 모두 2배 해야하는 경우
- for 반복문이 없이 간단. 단 한번의 연산식으로 표현
- 벡터화 연산은 비교 연산과 논리 연산을 포함한 모든 종류의 수학 연산에 대해 적용

In [231]:
# 데이터 2배
data = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
answer = [2 * d for d in data ]
answer

[0, 2, 4, 6, 8, 10, 12, 14, 16, 18]

In [232]:
# for 없이
x = np.array(data)
x
2 * x

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [233]:
list_samp = [_ for _ in range(3)]
print(list_samp *5)     # 0,1,2 5번 반복

[0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2]


In [235]:
a = np.array([1,2,3])
b = np.array([10,20,30])

In [236]:
2 * a + b

array([12, 24, 36])

In [237]:
a == 2

array([False,  True, False])

In [238]:
b > 10

array([False,  True,  True])

In [243]:
(a == 2 ) & (b > 10)    # &는 bit 연산자

array([False,  True, False])

### 2차원 배열
- 수학에서 행렬로 말함
- 리스트를 중첩 해 list of list를 이용해 2차원 배열처럼 생성
- 안쪽 리스트의 길이는 행렬의 열의 수 (가로크기)
- 바깥쪽 리스트는 행렬의 수 (세로크기)

In [248]:
c = np.array([[1,2,3],
             [4,5,6]])

In [249]:
c.shape

(2, 3)

In [250]:
len(c)

2

In [251]:
len(c[0])

3

In [258]:
np.array([[10,20,30,40],
        [50,60,70,80]])

array([[10, 20, 30, 40],
       [50, 60, 70, 80]])

### 3차원 배열
- 행렬을 겹겹이 쌓아 올린 구조 생각해보기
- 구조는 깊이 * 행 * 열 의 모양
- axis 0는 깊이를 의미,  axis 1는 행, axis 2는 열

In [271]:
# 2 * 3 * 4
d = np.array([[[1,2,3,4],
              [5,6,7,8],
              [9,10,11,12]],
             [[13,14,15,16],
              [17,18,19,20],
              [21,22,23,24]]])

#### 배열의 차원과 크기 알아내기
- 배열의 ndim 속성과 shape 속성을 이용 
- ndim 은 배열의 차원, shape 배열의 크기를 반환

In [272]:
# a = np.array([1,2,3])
print(a.ndim)
print(a.shape)

1
(3,)


In [273]:
# c = np.array([[0,1,2],[3,4,5]])
print(c.ndim)
print(c.shape)

2
(2, 3)


In [274]:
print(d.ndim)
print(d.shape)

3
(2, 3, 4)


- 일차원 배열의 인덱싱은 리스트와 비슷하다

In [277]:
a = np.array([_ for _ in range(5)])
a

array([0, 1, 2, 3, 4])

In [278]:
a[-1]

4

- 다차원 배열의 인덱싱은 리스트와 다르다

In [283]:
a = [[1,2,3],[4,5,6]]

In [284]:
list_samp[0][0]

1

- 배열 객체로 구현한 다차원 배열의 원소 중
- 복수 개를 접근 하려면 slicing , comma함께 사용하면 됨(슬라이싱, 콤마)

In [285]:
a  = np.array([[0,1,2,3],[4,5,6,7]])
a

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [290]:
a[0,:] # 첫번째 행 전체

array([0, 1, 2, 3])

In [291]:
a[0,:] # 두번째 열 전체

array([0, 1, 2, 3])

In [292]:
a[1,1:] # 두번째 행의 두번째 열부터 끝열까지

array([5, 6, 7])

In [294]:
a[:2,:2]

array([[0, 1],
       [4, 5]])

In [289]:
np.array([ _ for _ in range(8)]).reshape(2,4)

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [327]:
m = np.array([[0,1,2,3,4],
              [5,6,7,8,9],               # 1,3,5
              [10, 11, 12, 13, 14]])
m

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [328]:
num = np.array([_ for _ in range(15)]).reshape(3,5)

In [329]:
num[1,2]

7

In [330]:
num[2,4]

14

In [331]:
num[1,1:3]

array([6, 7])

In [332]:
num[1:,2]

array([ 7, 12])

In [333]:
num[:2,3:]

array([[3, 4],
       [8, 9]])

#### 배열 생성
##### 몇가지 단순한 배열을 생성하는 메서드를 제공
- zeros, ones
- zeros_like, ones_like
- empty ( 배열을 생성하고 특정한 값으로 초기화 하지 않는 명령어)
- arange 명령. NumPy 버전의 range 명령. 특정한 규칙에 따라 증가하는 수열
- linspace 나 logspace
- 전치(transpose)연산은 행과 열을 바꾸는 작업 / 배열의 T속성으로 구할 수 있음 메서드 아님

In [378]:
a = np.zeros(5)                         # <<<< float type
a

array([0., 0., 0., 0., 0.])

In [361]:
c = np.zeros((5,2),dtype = "i")         # <<<<  i 는 int
c

array([[0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0]], dtype=int32)

In [362]:
d = np.zeros(5,dtype = "U4")            # U4 / 문자 4글자까지만
d

array(['', '', '', '', ''], dtype='<U4')

In [363]:
d[0] = 'abc'
d[1] = 'abcd'
d[2] = 'abcde'
d

array(['abc', 'abcd', 'abcd', '', ''], dtype='<U4')

In [364]:
e = np.ones((2,3,4),dtype = "i8")       # 행의 깊이 
e                                       # 2,3,4

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]], dtype=int64)

In [365]:
f = np.ones_like(b, dtype = "f")       
f

array([1., 1., 1.], dtype=float32)

In [372]:
np.arange(10)               # 0 . . N-1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [373]:
np.arange(3,21,2)           # 시작, 끝(포함하지 않음), 단계

array([ 3,  5,  7,  9, 11, 13, 15, 17, 19])

In [374]:
np.linspace(0, 100, 5)      #시작, 끝(포함), 갯수

array([  0.,  25.,  50.,  75., 100.])

In [375]:
np.linspace(0, 100, 5)      #시작, 끝

array([  0.,  25.,  50.,  75., 100.])

In [377]:
ex = np.linspace(0, 100, 18)
ex

array([  0.        ,   5.88235294,  11.76470588,  17.64705882,
        23.52941176,  29.41176471,  35.29411765,  41.17647059,
        47.05882353,  52.94117647,  58.82352941,  64.70588235,
        70.58823529,  76.47058824,  82.35294118,  88.23529412,
        94.11764706, 100.        ])

In [380]:
A = np.array([[1,2,3],[4,5,6]])
A

array([[1, 2, 3],
       [4, 5, 6]])

#### 배열의 크기 변형
- reshape
- flatten 혹은 ravel

In [390]:
ex3 = np.arange(12)
ex3.reshape(2,2,-1)

array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]]])

#### 배열 연결 ####
##### 행의 수나 열의 수가 같은 두 개 이상의 배열을 연결. 더 큰배열을 연결할때
- hstack
- vstack
- dstack
- stack
- r_
- c_
- tile

In [393]:
b1 = np.ones((2,3))
b2 = np.zeros((3,3))
print(b1)
print(b2)

[[1. 1. 1.]
 [1. 1. 1.]]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [420]:
a1 = np.ones( (2, 3) )
a2 = np.zeros( (2, 2) )
np.hstack( [a1, a2] )

array([[1., 1., 1., 0., 0.],
       [1., 1., 1., 0., 0.]])

In [394]:
np.vstack([b1,b2])

array([[1., 1., 1.],
       [1., 1., 1.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [395]:
c = np.ones((3,4))
c 

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [398]:
c2 = np.zeros((3,4))
c2

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [400]:
np.dstack([c,c2])

array([[[1., 0.],
        [1., 0.],
        [1., 0.],
        [1., 0.]],

       [[1., 0.],
        [1., 0.],
        [1., 0.],
        [1., 0.]],

       [[1., 0.],
        [1., 0.],
        [1., 0.],
        [1., 0.]]])

In [413]:
c1 = np.ones( (3, 4) )
c2 = np.zeros( (3, 4) )
np.stack( [c1, c2] ) # stack 메서드 안에 axis = 0(기본값)

#3행 4열 짜리 배열 2개가 => 깊이가 2개인 3행 4열 됨
(2 * 3 * 4)

np.stack( [c1, c2], axis = 1 ) 

array([[[1., 1., 1., 1.],
        [0., 0., 0., 0.]],

       [[1., 1., 1., 1.],
        [0., 0., 0., 0.]],

       [[1., 1., 1., 1.],
        [0., 0., 0., 0.]]])

In [405]:
np.r_[np.array([1,2,3]), np.array([4,5,6])]

array([1, 2, 3, 4, 5, 6])

In [406]:
np.c_[np.array([1,2,3]), np.array([4,5,6]) ]

array([[1, 4],
       [2, 5],
       [3, 6]])

In [407]:
a = np.array([[0,2,3],[3,4,5]])
np.tile(a,2)

array([[0, 2, 3, 0, 2, 3],
       [3, 4, 5, 3, 4, 5]])

In [408]:
np.tile(a,(3,2))

array([[0, 2, 3, 0, 2, 3],
       [3, 4, 5, 3, 4, 5],
       [0, 2, 3, 0, 2, 3],
       [3, 4, 5, 3, 4, 5],
       [0, 2, 3, 0, 2, 3],
       [3, 4, 5, 3, 4, 5]])

In [431]:
a = np.zeros((3,3))
a2 = np.ones((3,2))
a3 = np.hstack([a,a2])
print(a3)
a4 = np.arange(10,160,10).reshape(-1,5)         #-1 알아서 해주세요 # 5행에 맞춰 알아서 해주세요
print(a4)


[[0. 0. 0. 1. 1.]
 [0. 0. 0. 1. 1.]
 [0. 0. 0. 1. 1.]]
[[ 10  20  30  40  50]
 [ 60  70  80  90 100]
 [110 120 130 140 150]]


In [435]:
a5 = np.vstack([a3,a4])
a5

array([[  0.,   0.,   0.,   1.,   1.],
       [  0.,   0.,   0.,   1.,   1.],
       [  0.,   0.,   0.,   1.,   1.],
       [ 10.,  20.,  30.,  40.,  50.],
       [ 60.,  70.,  80.,  90., 100.],
       [110., 120., 130., 140., 150.]])

In [436]:
np.vstack([a5,a5])

array([[  0.,   0.,   0.,   1.,   1.],
       [  0.,   0.,   0.,   1.,   1.],
       [  0.,   0.,   0.,   1.,   1.],
       [ 10.,  20.,  30.,  40.,  50.],
       [ 60.,  70.,  80.,  90., 100.],
       [110., 120., 130., 140., 150.],
       [  0.,   0.,   0.,   1.,   1.],
       [  0.,   0.,   0.,   1.,   1.],
       [  0.,   0.,   0.,   1.,   1.],
       [ 10.,  20.,  30.,  40.,  50.],
       [ 60.,  70.,  80.,  90., 100.],
       [110., 120., 130., 140., 150.]])