In [9]:
import numpy as np

### 230117 복습 ###

In [28]:
# Q 현재까지 계산한 값을 속성 value(class속성으로 볼껀지, 인스턴스 속성으로 볼껀지)로 갖는 계산기 클래스 만들기
#   range는 더할수가 없음. 값이 그때그때 바뀌어서
 
class Calculator:                         
    def __init__(self,value = 0):         # value 초기값은 '0'
        self.value = value                 

    def add(self,*args):                  # 가변인자( 활용
        if len(args) == 0:                # 인수가 없는경우('0') 숫자 입력해줘 / 크기를 모르니 len() 활용
            print("숫자를 입력해주세요")
            return                        # 인수가 없을때 처리를 하지 않는다
        a = np.array(args)                # 변수주고 np
        self.value += np.sum(a)           # value값에 인수로 받은 값을 가산 (NumPy sum활용)
                                    
    
    def minus(self,*args):
        if len(args) == 0:
            print("숫자를 입력해주세요")  
            return
        a = np.array(args)                
        self.value -= np.sum(a)           # value값에 인수로 받은 값을 감산 (NumPy활용)

    def show_value(self):
        print("현재 값은",self.value, "입니다.")
        

In [29]:
c = Calculator()

In [30]:
c.add(100)
c.minus(20)

In [31]:
c.show_value()    #80

현재 값은 80 입니다.


In [32]:
c.add()           #숫자를 입력해

숫자를 입력해주세요


In [33]:
c.minus([10,20])

In [34]:
c.show_value()     #50

현재 값은 50 입니다.


In [35]:
c.add(range(1,6))

In [36]:
c.show_value()     #65

현재 값은 65 입니다.


### NumPy
- 크기만 알면 type만큼 더해서 그값이 나옴 -> 어떤 dimensions을 통해 깔끔하게 내놓을것인가

### 벡터화 연산
- 넘파이 배열의 벡터화 연산은 간단하게 계산 가능 (%%time은 셀코드의 실행시간을 측정 : 아이파이썬, 매직아이)
- 사칙 연산, 비교 연산, 논리 연산 모두 벡터화 연산이 가능하다
- 배열의 각 원소들을 일일히 비교하는 것이 아닌, 배열의 모든 원소가 같은지 확인하려면 'all' 명령 사용 (np.all())

### 스칼라와 벡터/행렬의 곱셉
- 넘파이 배열에서 스칼라와 벡터/행렬의 곱도 선형대수에서 사용하는 식과 같이 표현 가능

### 브로드캐스팅  
- 보통 배열끼리 산술 연산을 하려면 두 배열의 shapes가 정확히 같아야함.
- 넘파이 배열은 모양이 다른 배열간의 연산이 가능. 배열의 크기를 변환(브로드캐스팅)지원
- 넘파이가 산술 연산 중에 모양이 다른 배열을 처리하는 방법
- 넘파이가 처리하는 브로드캐스팅의 방법은 더 작은 배열이 더 큰 배열에 호환되는 모양으로 확장
- 넘파이 배열의 shape을 우측 정렬하고 각 차원별로 숫자를 비교
#### 모든 경우에 브로드 캐스팅이 될수 있는가
- 비교하는 모든 차원의 두 조건 중 하나에 충족되어야 브로드 캐스팅 가능
-  a. 해당 차원 간의 숫자가 동일한 경우 /  b. 해당 차원중 하나가 1인 경우
- 결국 1이거나 같거나
- 3차원: 깊이x 행x 열 / 2차원: 행x 열 / 1차원: 열 (우측 정렬 후 확인)
#### 브로드 캐스팅이 불가능할때
- 각 차원의 숫자가 일치하지 않을 때( value error가 남 )
#### 브로드 캐스팅 규칙
- 배열과 스칼라 값이 연산에서 결합
- 더 적은 메모리를 이용하기 때문에 스칼라 곱이 빠름

In [40]:
# 스칼라 곱
a = np.array([1.0,2.0,3.0])
b = 2.0
a*b

array([2., 4., 6.])

### 차원 축소 연산
- 행렬의 하나의 행에 있는 원소들을 하나의 데이터 집합으로 보고, 그 집합의 평균을 구하면 각 행에 대해 하나의 숫자가 나옴
- ex) 10 * 5 크기의 2차원 배열에 행-평균을 구하면 10개의 숫자를 가진 1차원 벡터가 나옴(차원축소연산)
- 넘파이 차원축소 연산 명령 or  메서드를 지원
- 최대/최소 : min, max, argmin, argmax
- 통계 : sum, mean, median, std, var(분산)
- 불리언 : all, any

### 차원축소 연산 - sum()
- 해당 배열의 합산 결과 반환. 연산대상이 2차원 이상일 때에는 axis키워드 인수 사용
- np.sum()과 ndarray.sum()은 동등한 메서드

In [106]:
x = np.array([1,2,3,4])
x

array([1, 2, 3, 4])

In [107]:
np.sum(x)

10

In [108]:
x.sum()

10

In [109]:
x = np.arange(12).reshape(3,-1)
x

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [110]:
x.sum(axis = 0)         # axis = 0 은 행 간의 연산결과를 구함

array([12, 15, 18, 21])

In [111]:
x.sum(axis = 1)         # axis = 0 은 행 간의 연산결과를 구함

array([ 6, 22, 38])

### 차원축소 연산 - min()
- 해당 배열의 제일 작은 값의 결과를 반환. 2차원 이상일 때는 axis키워드 인수 사용


In [112]:
x = np.arange(20).reshape(2,5,-1)
x

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7],
        [ 8,  9]],

       [[10, 11],
        [12, 13],
        [14, 15],
        [16, 17],
        [18, 19]]])

In [113]:
x.min()

0

In [114]:
np.min(x)

0

In [115]:
x.min(axis = 0)

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [116]:
np.min(x, axis = 1)

array([[ 0,  1],
       [10, 11]])

In [117]:
x.min(axis = 2)

array([[ 0,  2,  4,  6,  8],
       [10, 12, 14, 16, 18]])

### 차원축소 연산 - argmin() 
- 해당 배열의 제일 작은 값의 인덱스를 반환. 2차원 이상일 때 동일

### 차원축소 연산 - max()
- 제일 큰 값의 결과를 반환. 2차원 동일

### 차원축소 연산 - argmax()
- 제일 큰 값의 인덱스를 반환

### 차원축소 연산 
- mean() 평균
- median()중앙 값 
- np.all().모든 요소가 T일때 T 
- np.any() 하나라도 T일때 T

In [118]:
practice = np.array([[1.1, 7.1, 8.0, 2.1, 6.5, 7.2],
                     [2.7, 5.2, 3.3, 9.0, 7.7, 2.8],
                     [0.7, 8.8, 4.2, 8.9, 4.3, 7.4],
                     [8.2, 1.1, 5.4, 2.9, 6.9, 0.2],
                     [7.4, 4.8, 2.7, 3.1, 2.8, 8.9]])


In [119]:
practice.max()

9.0

In [120]:
np.sum(practice, axis = 0)

array([20.1, 27. , 23.6, 26. , 28.2, 26.5])

In [121]:
np.max(practice,axis = 0)

array([8.2, 8.8, 8. , 9. , 7.7, 8.9])

In [122]:
np.mean(practice,axis = 1)

array([5.33333333, 5.11666667, 5.71666667, 4.11666667, 4.95      ])

In [123]:
np.min(practice,axis = 1)

array([1.1, 2.7, 0.7, 0.2, 2.7])

## 정렬
- numpy.sort()를 사용. 배열 안의 원소를 크기에 따라 정렬 -> 새로운 배열을 만듬
- 2차원 이상인 경우 == 행, 열을 각각 따로 'axis' 인수를 사용 (행을 정렬할건지, 열을 정렬할 건지 결정)
1. axis = 0 이면 각각의 행을 따로 정렬
2. axis = 1 이면 각각의 열을 따로 정렬
3. axis = -1 디폴트 값은 -1 즉 가장 안쪽(나중)의 차원

- ndarray.sort() 메서드는 해당 객체의 자료 자체가 변화하는 자체 변화(in-place) 메서드(주의필요)
- 자료를 정렬하는 것이 아니라 순서만 알고싶다면 argsort명령 사용

In [157]:
a = np.array([[4,3,5,7],
              [1,12,11,9],
              [2,15,1,14]])
a

array([[ 4,  3,  5,  7],
       [ 1, 12, 11,  9],
       [ 2, 15,  1, 14]])

In [131]:
np.sort(a)       # axis = -1 과  axis = 1 과 동일

array([[ 3,  4,  5,  7],
       [ 1,  9, 11, 12],
       [ 1,  2, 14, 15]])

In [132]:
np.sort(a, axis = 0) 

array([[ 1,  3,  1,  7],
       [ 2, 12,  5,  9],
       [ 4, 15, 11, 14]])

In [144]:
a = np.array([42,38,12,25])
j = np.argsort(a)             #순서를 가져올수 있음
j                             # 작은것부터 순서대로

array([2, 3, 1, 0], dtype=int64)

In [145]:
a[j]                          # 인덱싱

array([12, 25, 38, 42])

In [146]:
np.sort(a)

array([12, 25, 38, 42])

### 고급 인덱싱 - 인덱스 배열을 사용한 인덱싱

In [190]:
a = np.array([[1,2],[3,4],[5,6]])
a

array([[1, 2],
       [3, 4],
       [5, 6]])

In [191]:
print(a[[0,1,2],[0,1,0]])    # # a[0,0] a[1,1] a[2,0]을 인덱스로 함 

[1 4 5]


In [192]:
 a = np.array([[1,2],[3,4],[5,6]])
a

array([[1, 2],
       [3, 4],
       [5, 6]])

In [193]:
print(a[:,[0,1,0]])

[[1 2 1]
 [3 4 3]
 [5 6 5]]


In [218]:
# Q 다음 배열은 첫번째행 (row)에 학번, 두번째 행에 영어성적, 세번째 행에 수학성적을 적은 배열이다.
#   영어 성적을 기준으로 각 열(column)을 재정렬해라

scores = np.array([[1,2,3,4,],
                   [46,99,100,71],
                   [81,59,90,100]])

In [215]:
# 1

print(scores[:,[0,3,1,2]])    # [: 인덱스 전체 끝까지

[[  1   4   2   3]
 [ 46  71  99 100]
 [ 81 100  59  90]]


In [219]:
# 2

j = np.argsort(scores[1])
print(scores[:,j])          # : <<-- [[0,1,2] : [0,3,1,2]]

[[  1   4   2   3]
 [ 46  71  99 100]
 [ 81 100  59  90]]


### 기술 통계
#### 데이터 집합에 대해 간단한 통계를 계산하는 함수 제공 : 기술통계

### 데이터의 개수
#### len()함수로 구할수 있음    len(a)

### 표본 평균 
#### 평균을 통계용어로 표본 평균이라고 함. np.mean(a) #평균

### 표본 분산
#### 데이터와 표본 평균간의 거리의 제곱의 평균    np.var()

### 표본 표준편차
#### 표본분산 np.std(a)

### 사분위수
#### 가장 작은 수부터 가장 큰 수까지 크기가 커지는 순서대로 정렬 했을때 구간마다의 수치를 구하는 것. 
#### 2사분위수는 중앙값과 같다. # np.percentile(50)  # 2사분위수
#### 백분위수를 사용하기도 한다. np.percentile(100) # 최대값

### 난수 발생과 카운팅
#### 데이터를 무적위로 섞거나 임의의 수 : 난수... 를 발생시키는 방법 NumPy의 random 서브 패키지에서 제공.(표준패키지랑 다름)

### 시드 설정하기
- 어떤 특정한 시작 숫자를 정하면 알고리즘에 의해 난수처럼 보이는 수열을 생성
- 기준이 되는 시작 숫자를 시드(seed)라고 함
- 생성된 난수는 다음 번 난수 생성을 위한 시드값이 됨 - > 시드값은 한 번만 정하자
- np.random.seed(0)    - > 인수로는 0과 같거나 큰정수를 넣어준다

In [220]:
np.random.seed(0)

In [221]:
np.random.rand(5)

array([0.5488135 , 0.71518937, 0.60276338, 0.54488318, 0.4236548 ])

In [222]:
np.random.rand(10)

array([0.64589411, 0.43758721, 0.891773  , 0.96366276, 0.38344152,
       0.79172504, 0.52889492, 0.56804456, 0.92559664, 0.07103606])

In [223]:
np.random.rand(10)

array([0.0871293 , 0.0202184 , 0.83261985, 0.77815675, 0.87001215,
       0.97861834, 0.79915856, 0.46147936, 0.78052918, 0.11827443])

### 데이터의 순서 바꾸기
#### shuffle 함수 / 자체 변환 함수로 한번 사용하면 변수의 값이 바뀜(주의필요)
- 순서를 랜덤하게 바꾸고 싶으면 shuffle함수를 사용

In [224]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [225]:
np.random.shuffle(x)
x

array([3, 6, 4, 5, 2, 9, 7, 8, 1, 0])

### 데이터 샘플링
#### 이미 있는 데이터 집합에서 일부를 무작위로 선택 : 표본선택 or 샘플링(sampling)
- 샘플링에는 choice함수 사용 
#### numpy.random.choice(a, size = None, replace = True, p = None)
- a : 배열이면 원래의 데이터, 정수이면 arange(a)명령으로 데이터 생성
- size : 정수. 샘플 숫자.
- replace : 불리언. T면 한번 선택한 데이터를 다시 선택가능
- p : 배열. 각 데이터가 선택될 수 있는 확률

##### 첫인수를 정수 5로 전달하여 np.arange(5)의 결과 만들었다

In [226]:
np.random.choice(5,5,replace = False) # shuffle 명령과 같다

array([1, 4, 0, 3, 2])

In [227]:
np.random.choice(5,3, replace = False) # 3개만 선택

array([2, 1, 3])

In [231]:
np.random.choice(5,10)           #반복해서 10개 선택

array([0, 1, 1, 3, 0, 0, 1, 2, 4, 2])

In [230]:
# 
np.random.choice(5,10,p=[0.1,0.,0.3,0.6,0])     # 선택 확률을 다르게 해서 10개 선택

array([3, 3, 3, 3, 3, 3, 3, 3, 2, 3])

### 난수 생성
#### 넘파이의 random서브패키지 중 난수생성하는 함수
1. rand : 0부터 1사이의 균일 분포
- 실수 난수를 생성. 숫자 인수는 생성할 난수의 크기. 
2. randn : 표준 정규 분포
- 기대값(mean)이 0 이고 표준편차가 표준 정규 분포를 따르는 1인 난수를 생성
3. randint : 균일 분포의 정수 난수
- numpy.random.randint(low,high = None, size=None)
- 만약 high 를 입력하지 않으면, 0과 low 사이의 숫자를 ///// // high를 입력하면, low와 high사이의 숫자 출력
- size는 난수의 개수, high 의 범위는 포함하지 않음

In [242]:
# Q 동전을 100번 던진 결과를 넘파이에 난수를 발생시켜서 시뮬레이션해보려 한다.
# 앞면을 숫자 1, 뒷면을 숫자 0 으로 가정하고 난수를 발생시켜보세요. 이때 앞면이 나올 확률을 구하는 프로그램을 구현해보라.
# (seed는 0으로)    # 0.56

np.random.seed(0)
num = np.random.randint(0,2,100)
np.count_nonzero(num == 1)/100

0.56

In [250]:
#1
sum(num)/ len(num)

0.56

In [251]:
#2

np.sum(num)/100

0.56

In [252]:
#3

list(num).count(1) / 100

0.56

In [253]:
# 주사위는 1부터 6까지의 숫자를 가진다. 이 주사위를 100번 던져서 나오는 숫자를 넘파이 난수를 발생시켜서 
# 시뮬레이션하고 나오는 숫자의 평균을 구해봐라. (seed는 0으로 설정합니다)

np.random.seed(0)
num2 = np.random.randint(1,7,100)
np.mean(num2)

3.42

### 정수 데이터 카운팅
- 난수가 정수 값이면 unique 명령이나 bincount명령으로 데이터 값 분석 가능
- unique() 함수는 중복된 값을 제거. 중복되지 않는 값의 리스트(몸통)를 출력
- return_counts 인수를 True로 설정 시 -> 각 값의 데이터 개수 출력
- 존재하는 값에 대해서만 개수를 counting함. 데이터가 없는 경우 정보를 주지 않음. 
- bincount함수는 0부터  minlength -1 까지의 숫자에 대해 각각 카운트를 한다.
- (특정범위 안의 수인 경우 bincount함수는 minlength 인수를 설정해 사용:편리)

In [256]:
np.bincount([1,1,2,2,2,3],minlength = 6)

array([0, 2, 3, 1, 0, 0], dtype=int64)